### ISSUE TITLE
@cache_for_request doesn't work when method returns a Pandas dataframe

### ISSUE THREAD

**Issue by danielbenami** [anexia/django-request-cache#10]
Hello,

Thanks so much for putting this together. When I try to use @cache_for_request on class methods that return a Pandas dataframe I get the following error: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Exception Location: | /Users/dbenami/Dev/ImpactTracker/src/ImpactTracker/lib/python3.7/site-packages/pandas/core/generic.py in __nonzero__, line 1479
-- | --

Please let me know if there is more useful information I can share. In the meanwhile I still find your package useful for reducing sql queries.

**Comment by nezhar** [comment]
I'm unsure if the issue was linked to a previous version of pandas, but with the latest release, there are no problems, see #18
