### ISSUE TITLE
Replace userforeignkey with crum?

### ISSUE THREAD

**Issue by valentijnscholten** [anexia/django-request-cache#12]
I noticed the the https://pypi.org/project/django-userforeignkey/ hasn't been updated for 2,5 years, doesn't support Django 2.2 or 3.x and its homepage link leads to https://ks.co.at/ which shows nothing but an invalid ssl certificate warning.

I was checking it out, because in my projects I am using https://pypi.org/project/django-crum/ and was wondering if I should remove that one as having 2 libraries to capture the current request seems a bit overkill.

But it looks like `crum` might actually be a better choice. Its main purpose is to capture the request and current user, where the other one also added some ORM related stuff. It supports Django 2.2, and 3.x and python 3.6/7/8/9.

What do you think?

**Comment by nezhar** [comment]
Thanks for the suggestion. As we help maintaining https://pypi.org/project/django-userforeignkey/ and it fits our scope we don't consider a switch. Also it seems that the suggested package is no longer maintained.
